name: Full iOS PR

on:
  pull_request:
    paths:
      - 'PrebidMobile/**'
      - 'EventHandlers/**'
      - 'scripts/**'
      - 'PrebidMobileTests/**'
      - 'Podfile'
      - 'Podfile.lock'
      - '.github/workflows/**'
    types: [opened, reopened, synchronize, ready_for_review, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    tests:
      runs-on: macos-15
      if: >-
        ${{
        github.event_name == 'workflow_dispatch' ||
        (
          github.event_name == 'pull_request' &&
          (
            contains(github.head_ref || '', 'bump-to') ||
            (
              github.event.pull_request != null &&
              contains(toJson(github.event.pull_request.labels) || '', 'run-full-tests')
            )
          )
        )
        }}
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build via script
        run: echo "Running FULL test suite or expensive jobs"


